In [2]:
import numpy as np

#### Задание 1

In [3]:
a = np.array([[1,2,3,3,1],[6,8,11,10,7]])
mean_a = np.zeros(2,)

In [4]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [5]:
np.mean(a, axis = 1, out = mean_a)

array([2. , 8.4])

In [6]:
mean_a

array([2. , 8.4])

#### Задание 2 ####

In [7]:
a_centered = np.zeros_like(a)
a_centered = a - mean_a.reshape(2,1)
print (a_centered)


[[-1.   0.   1.   1.  -1. ]
 [-2.4 -0.4  2.6  1.6 -1.4]]


In [8]:
a_centered

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

#### Задание 3

In [9]:
a_centered_sp = np.dot(a_centered[0], a_centered[1])
print (a_centered_sp)

8.0


In [10]:
a_centered_sp / (a.shape[0]-1)

8.0

In [11]:
print(a_centered_sp / (a.shape[0] + a.shape[1] - 1) )

1.3333333333333333


### Тема “Работа с данными в Pandas”

In [10]:
import pandas as pd
authors = pd.DataFrame(np.array([[1,'Тургенев'], [2,'Чехов'], [3,'Островский']]), columns=['author_id','author_name'])
authors['author_id'] = pd.to_numeric(authors['author_id'])
authors.set_index('author_id')
#print (authors)

author_name
author_id            
1            Тургенев
2               Чехов
3          Островский

In [11]:
d0 = {'r0': [1, 1, 1, 2, 2, 3, 3],
'r1' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
'r2' : [450, 300, 350, 500, 450, 370, 290]}

book1 = pd.DataFrame(data = d0)#, columns=['author_id', 'book_title', 'price'])
book = book1.rename(columns = {'r0':'author_id', 'r1':'book_title', 'r2':'price'})
book.set_index('author_id')
#print (book)

book_title  price
author_id                             
1                   Отцы и дети    450
1                         Рудин    300
1             Дворянское гнездо    350
2              Толстый и тонкий    500
2               Дама с собачкой    450
3                         Гроза    370
3          Таланты и поклонники    290

In [12]:
authors_price = book.merge(authors, how='left', on = ['author_id'])
#authors_price = book.join(authors)
print (authors_price)

   author_id            book_title  price author_name
0          1           Отцы и дети    450    Тургенев
1          1                 Рудин    300    Тургенев
2          1     Дворянское гнездо    350    Тургенев
3          2      Толстый и тонкий    500       Чехов
4          2       Дама с собачкой    450       Чехов
5          3                 Гроза    370  Островский
6          3  Таланты и поклонники    290  Островский


In [13]:
authors_price.sort_values(by = ['price'], ascending = False)
top5 = authors_price.iloc[0:5]
print (top5)

   author_id         book_title  price author_name
0          1        Отцы и дети    450    Тургенев
1          1              Рудин    300    Тургенев
2          1  Дворянское гнездо    350    Тургенев
3          2   Толстый и тонкий    500       Чехов
4          2    Дама с собачкой    450       Чехов


In [14]:
authors_stat = authors_price.groupby('author_name')
authors_stat = authors_stat['price'].agg([np.min, np.max, np.mean])
print (authors_stat)

             amin  amax        mean
author_name                        
Островский    290   370  330.000000
Тургенев      300   450  366.666667
Чехов         450   500  475.000000
